- name: tags on tasks
  hosts: all
  tasks:
     - debug: msg="Installing Web Service"
       tags:
     - WEB
     - debug: msg="Starting Web Service"
       tags:
     - WEB
     - debug: msg="Installing App Service"
       tags:
     - APP
     - debug: msg="Starting App Service"
       tags:
     - APP
